/* Generated by Opal 0.6.2 */
(function($opal) {
  var $a, $b, TMP_1, self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, result = nil;

  $opal.add_stubs(['$==', '$%', '$===', '$to_s', '$join', '$collect', '$fizzbuzz', '$+', '$times']);
  $opal.Object._proto.$fizzbuzz = function(number) {
    var self = this, $case = nil;

    return (function() {$case = [number['$%'](3)['$=='](0), number['$%'](5)['$=='](0)];if ([true, true]['$===']($case)) {return "FizzBuzz"}else if ([true, false]['$===']($case)) {return "Fizz"}else if ([false, true]['$===']($case)) {return "Buzz"}else {return number.$to_s()}})();
  };
  result = ($a = ($b = (100).$times()).$collect, $a._p = (TMP_1 = function(x){var self = TMP_1._s || this;
if (x == null) x = nil;
  return self.$fizzbuzz(x['$+'](1))}, TMP_1._s = self, TMP_1), $a).call($b).$join("<br />");
  return document.write(result);
})(Opal);
